# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'THW iPad' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for THW iPad

  target 'THW iPadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'THW iPadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
